<a href="https://colab.research.google.com/github/Xantosh/FreeCodeCamp-Data-Analysis/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vectorized operations

In [2]:
import numpy as np

In [6]:
a = np.arange(5) #produces an npa rray starting from 0 to n-1.
a

array([0, 1, 2, 3, 4])

In [7]:
a + 10   #add a scalar value to all elements of array

array([10, 11, 12, 13, 14])

In [8]:
a * 10  #all the arithemtic operations on array with scalar will be operated on each elemnts.

array([ 0, 10, 20, 30, 40])

In [9]:
a += 100 # similar to a = a + 100 but on array

In [10]:
a

array([100, 101, 102, 103, 104])

In [18]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

#Broadcasting

Note: it is different for multiplication as every element multiplies and is not as dot product.

In [16]:
a + b  #for the arithmetic oprations between array sthey must be of same size.

array([100, 102, 104, 106, 108])

In [17]:
a * b

array([  0, 101, 204, 309, 416])

In [19]:
a[[0,-1]]

array([100, 104])

In [21]:
a[[True,False,True,False,True]] #choosing elements based on boolean values.

array([100, 102, 104])

In [22]:
a  >= 2 #comparing an array with constant returns boolean array.

array([ True,  True,  True,  True,  True])

In [23]:
a[a >= 2] #return array based on the conditions inside square bracket.

array([100, 101, 102, 103, 104])

In [29]:
c = np.random.randint(1,5,size = (2,2))
c

array([[4, 3],
       [3, 4]])

Note : '|' represents OR and '&' represnts AND