<a href="https://colab.research.google.com/github/Xantosh/FreeCodeCamp-Data-Analysis/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np #importing numpy library

In [11]:
a = np.array([1,2,3,4]) #creating 1-d numpy arrays
b = np.array([0,1,-2,4,5])

In [12]:
a[0],b[4] #accessing the array elemnts ..same as python list

(1, 5)

In [14]:
print(a[0:]) #slicing works on same way
print(a[1:3]) #last index is n-1.

[1 2 3 4]
[2 3]


In [18]:
b[:-1] #negative indexing saimilar goes up n-1.

array([ 0,  1, -2,  4])

In [21]:
b[:2:-1] #f -ve increment gicen even not specified goes from last to specified index-1.

array([5, 4])

In [22]:
b[[0,-1,-2]] #supports multi indexing and returns another numpy array.

array([0, 5, 4])

In [23]:
a.dtype #gives the data type of the number associated with it.

dtype('int64')

In [25]:
np.array(b,dtype=np.int8) #can convert the data type using np method.

array([ 0,  1, -2,  4,  5], dtype=int8)

In [27]:
c = np.array(['a','b','c']) #can store strings.
c.dtype #unicode representation.

dtype('<U1')

# Multi Dimensional Arrays



In [33]:
m = np.array([
     [1,2,3],
     [4,5,6],
     [7,8,9]
])

In [34]:
m.shape # output (row,column)

(3, 3)

In [35]:
m.ndim #gives the dimension of array

2

In [36]:
m.size # gives the total bo of elements.

9

In [41]:
n = np.array([[[1,2,3],
               [4,5,6]],
              [
               [7,8,9],
               [1,1,1]],
               [
                [2,2,3],
                [7,8,9]
               ]
            ])

In [42]:
n.shape

(3, 2, 3)

In [43]:
n.ndim

3

In [44]:
n.size

18

Note:If the dimension dont match np array falls to regular list on python.


#Indexing and slices of matrices.

In [49]:
#square matrices
A = np.array([
     #  0 1 2       
       [7,8,9], #0
       [3,4,5], #1
       [1,1,1]  #2        
])

In [48]:
A[1] #similar to list extracts the 2nd row as index starts from 0.

array([3, 4, 5])

In [50]:
A[0][0] #accessing individual elemnts.

7

In [52]:
A[0,0] #multidimensional selection of elements.

7

In [53]:
A[0:2] #slicing for extracting rows.

array([[7, 8, 9],
       [3, 4, 5]])

In [54]:
A[: , :2] # getting the matrix of some order selectiong the rows and columns

array([[7, 8],
       [3, 4],
       [1, 1]])

In [55]:
A[0] = np.array([0,0,0]) #if dimensions match replace row 0.

In [56]:
A

array([[0, 0, 0],
       [3, 4, 5],
       [1, 1, 1]])

In [57]:
A[1] = 2  #replaces the entire row with the given number.
A

array([[0, 0, 0],
       [2, 2, 2],
       [1, 1, 1]])

#Summary Stastics

In [58]:
s = np.array([1,2,3,4])


In [59]:
s.sum() #gives the total sum of elemnts.

10

In [60]:
s.mean() #gives the average of all elemnts in an array.

2.5

In [61]:
s.std() #gives the standard deviation.

1.118033988749895

In [62]:
s.var() #gives the variance of the elemnts.

1.25

Note: Works for multi dim array.

In [63]:
B = np.array([
     #  0 1 2       
       [7,8,9], #0
       [3,4,5], #1
       [1,1,1]  #2        
])

In [64]:
B.sum(axis=0) #returns array giving sum of individual elemets of column for if axis=0

array([11, 13, 15])

In [65]:
B.sum(axis=1) # returns array of sum of individual elemensts of row for x = 1

array([24, 12,  3])

In [67]:
n3 = np.array([[[1,2,3],
               [4,5,6]],
              [
               [7,8,9],
               [1,1,1]],
               [
                [2,2,3],
                [7,8,9]
               ]
            ])

In [69]:
n3.sum(axis=(1))

array([[ 5,  7,  9],
       [ 8,  9, 10],
       [ 9, 10, 12]])