<a href="https://colab.research.google.com/github/Xantosh/FreeCodeCamp-Data-Analysis/blob/main/Numpy_Algebra_and_Size.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra


In [12]:
import numpy as np
import sys

In [3]:
a = np.array([
              [1,2,3],
              [4,5,6],
              [7,8,9]
])                    

In [4]:
b = np.array([
              [1],
              [2],
              [3]
])

In [5]:
a.dot(b)  #equivalent to matrix multiplication aslong as n = m.

array([[14],
       [32],
       [50]])

In [6]:
a @ b   #cross product

array([[14],
       [32],
       [50]])

In [7]:
a.T #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [13]:
sys.getsizeof(1) #import sys to get the memory size using syze of

28

In [19]:
f = list(range(1000))
%time sum([x ** 2 for x in f])

CPU times: user 379 µs, sys: 44 µs, total: 423 µs
Wall time: 432 µs


332833500